# Generated by Django 5.1.3 on 2024-11-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("titleType", models.CharField(max_length=50)),
                ("primaryTitle", models.CharField(max_length=255)),
                ("originalTitle", models.CharField(max_length=255)),
                ("isAdult", models.BooleanField()),
                ("startYear", models.CharField(max_length=4)),
                ("endYear", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "runtimeMinutes",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("genres", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "nconst",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("primaryName", models.CharField(max_length=255)),
                ("birthYear", models.CharField(blank=True, max_length=4, null=True)),
                ("deathYear", models.CharField(blank=True, max_length=4, null=True)),
                ("primaryProfession", models.CharField(max_length=255)),
                ("knownForTitles", models.CharField(max_length=255)),
            ],
        ),
    ]
